# Generated by Django 3.2.22 on 2023-10-13 15:40

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20231013_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='studentlab2',
            name='signal',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0,1]*$')], verbose_name='Сигнал'),
        ),
        migrations.AlterField(
            model_name='studentlab3',
            name='signal',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[0,1]*$')], verbose_name='Сигнал'),
        ),
        migrations.AlterField(
            model_name='studentlab4',
            name='signal',
            field=models.CharField(max_length=96, validators=[django.core.validators.RegexValidator('^[0,1]*$')], verbose_name='Сигнал'),
        ),
    ]
