# Generated by Django 3.2.22 on 2023-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_student_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('2-PSK', '2-PSK (Фазовая манипуляция)'), ('4-PSK', '4-PSK (Фазовая манипуляция)'), ('8-PSK', '8-PSK (Фазовая манипуляция)'), ('16-PSK', '16-PSK (Фазовая манипуляция)'), ('32-PSK', '32-PSK (Фазовая манипуляция)'), ('4-QAM', '4-QAM (Квадратурно-амплитудная манипуляция)'), ('16-QAM', '16-QAM (Квадратурно-амплитудная манипуляция)'), ('64-QAM', '64-QAM (Квадратурно-амплитудная манипуляция)'), ('256-QAM', '256-QAM (Квадратурно-амплитудная манипуляция)')], max_length=7, verbose_name='Тип модуляции')),
                ('stars_image', models.ImageField(blank=True, max_length=200, upload_to='models.Modulation.stars_image/', verbose_name='Сигнальное созвездие')),
            ],
        ),
    ]
