# Generated by Django 3.2.22 on 2023-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0005_modulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='detect/models.TemporaryImage.image/%Y/', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='modulation',
            name='stars_image',
            field=models.ImageField(blank=True, max_length=200, upload_to='detect/models.Modulation.stars_image/', verbose_name='Сигнальное созвездие'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='detect/models.Question.image/', verbose_name='Картинка к вопросу'),
        ),
        migrations.AlterField(
            model_name='studentlab2',
            name='signal_image',
            field=models.ImageField(blank=True, max_length=200, upload_to='detect/models.StudentLab2.signal_image/%Y/', verbose_name='Изображение сигнала'),
        ),
        migrations.AlterField(
            model_name='studentlab2',
            name='stars_image',
            field=models.ImageField(blank=True, max_length=200, upload_to='detect/models.StudentLab2.stars_image/%Y/', verbose_name='Сигнальное созвездие'),
        ),
        migrations.AlterField(
            model_name='studentlab4',
            name='signal_image',
            field=models.ImageField(blank=True, max_length=200, upload_to='detect/models.StudentLab4.signal_image/%Y/', verbose_name='Изображение сигнала'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
