# Generated by Django 3.2.22 on 2023-10-14 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_auto_20231014_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlab3',
            name='multiplier',
            field=models.PositiveIntegerField(default=1, verbose_name='Множитель длины сигнала'),
        ),
        migrations.AlterField(
            model_name='studentlab2',
            name='signal',
            field=models.CharField(default='', max_length=32, validators=[django.core.validators.RegexValidator('^[0,1]*$')], verbose_name='Сигнал'),
        ),
        migrations.AlterField(
            model_name='studentlab3',
            name='signal',
            field=models.CharField(default='', max_length=48, validators=[django.core.validators.RegexValidator('^[0,1]*$')], verbose_name='Сигнал'),
        ),
    ]
