# Generated by Django 3.2 on 2021-05-23 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('family', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('percent', models.IntegerField(verbose_name='Процент выполнения')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
